project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Happy Planet"
  author:
    - Xinqing Diao (xd2324)
    - Han Qiang (hq2218)
  repo-url: https://github.com/saradiao92/happyplanet
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


